from enum import StrEnum


class JobStatus(StrEnum):
    CREATED = "CREATED"
    PENDING_SCRIPT = "PENDING_SCRIPT"
    SCRIPTING = "SCRIPTING"
    PENDING_CLIPS = "PENDING_CLIPS"
    CLIPPING = "CLIPPING"
    PENDING_VO = "PENDING_VO"
    VO = "VO"
    PENDING_RENDER = "PENDING_RENDER"
    RENDERING = "RENDERING"
    PENDING_PUBLISH = "PENDING_PUBLISH"
    PUBLISHING = "PUBLISHING"
    DONE = "DONE"
    FAILED = "FAILED"
    DEAD_LETTER = "DEAD_LETTER"
